# Generated by Django 3.2.2 on 2021-05-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20210513_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn_number',
            new_name='number',
        ),
    ]
